window.esdocSearchIndex = [
  [
    "5rolli-crx/src/content/lib/renderer.js~renderer",
    "class/src/content/lib/Renderer.js~Renderer.html",
    "<span>Renderer</span> <span class=\"search-result-import-path\">5rolli-crx/src/content/lib/Renderer.js</span>",
    "class"
  ],
  [
    "5rolli-crx/src/content/components/timesummarylabel.js~timesummarylabel",
    "function/index.html#static-function-TimeSummaryLabel",
    "<span>TimeSummaryLabel</span> <span class=\"search-result-import-path\">5rolli-crx/src/content/components/TimeSummaryLabel.js</span>",
    "function"
  ],
  [
    "5rolli-crx/src/content/timesummarymanager.js~timesummarymanager",
    "class/src/content/TimeSummaryManager.js~TimeSummaryManager.html",
    "<span>TimeSummaryManager</span> <span class=\"search-result-import-path\">5rolli-crx/src/content/TimeSummaryManager.js</span>",
    "class"
  ],
  [
    "5rolli-crx/src/content/helpers.js~createtime",
    "function/index.html#static-function-createTime",
    "<span>createTime</span> <span class=\"search-result-import-path\">5rolli-crx/src/content/helpers.js</span>",
    "function"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "",
    "test-file/test/content/TimeSummaryManager-spec.js.html#lineNumber8",
    "TimeSummaryManager",
    "test"
  ],
  [
    "",
    "test-file/test/content/TimeSummaryManager-spec.js.html#lineNumber13",
    "TimeSummaryManager is defined",
    "test"
  ],
  [
    "src/content/timesummarymanager.js",
    "file/src/content/TimeSummaryManager.js.html",
    "src/content/TimeSummaryManager.js",
    "file"
  ],
  [
    "src/content/timesummarymanager.js~timesummary",
    "typedef/index.html#static-typedef-TimeSummary",
    "src/content/TimeSummaryManager.js~TimeSummary",
    "typedef"
  ],
  [
    "src/content/timesummarymanager.js~timesummarymanager#constructor",
    "class/src/content/TimeSummaryManager.js~TimeSummaryManager.html#instance-constructor-constructor",
    "src/content/TimeSummaryManager.js~TimeSummaryManager#constructor",
    "method"
  ],
  [
    "src/content/timesummarymanager.js~timesummarymanager#gettimesummaries",
    "class/src/content/TimeSummaryManager.js~TimeSummaryManager.html#instance-method-getTimeSummaries",
    "src/content/TimeSummaryManager.js~TimeSummaryManager#getTimeSummaries",
    "method"
  ],
  [
    "src/content/timesummarymanager.js~timesummarymanager#observer",
    "class/src/content/TimeSummaryManager.js~TimeSummaryManager.html#instance-member-observer",
    "src/content/TimeSummaryManager.js~TimeSummaryManager#observer",
    "member"
  ],
  [
    "src/content/timesummarymanager.js~timesummarymanager#refresh",
    "class/src/content/TimeSummaryManager.js~TimeSummaryManager.html#instance-method-refresh",
    "src/content/TimeSummaryManager.js~TimeSummaryManager#refresh",
    "method"
  ],
  [
    "src/content/timesummarymanager.js~timesummarymanager#refreshtimeoutid",
    "class/src/content/TimeSummaryManager.js~TimeSummaryManager.html#instance-member-refreshTimeoutId",
    "src/content/TimeSummaryManager.js~TimeSummaryManager#refreshTimeoutId",
    "member"
  ],
  [
    "src/content/timesummarymanager.js~timesummarymanager#renderer",
    "class/src/content/TimeSummaryManager.js~TimeSummaryManager.html#instance-member-renderer",
    "src/content/TimeSummaryManager.js~TimeSummaryManager#renderer",
    "member"
  ],
  [
    "src/content/timesummarymanager.js~timesummarymanager#start",
    "class/src/content/TimeSummaryManager.js~TimeSummaryManager.html#instance-method-start",
    "src/content/TimeSummaryManager.js~TimeSummaryManager#start",
    "method"
  ],
  [
    "src/content/timesummarymanager.js~timesummarymanager#target",
    "class/src/content/TimeSummaryManager.js~TimeSummaryManager.html#instance-member-target",
    "src/content/TimeSummaryManager.js~TimeSummaryManager#target",
    "member"
  ],
  [
    "src/content/components/timesummarylabel.js",
    "file/src/content/components/TimeSummaryLabel.js.html",
    "src/content/components/TimeSummaryLabel.js",
    "file"
  ],
  [
    "src/content/helpers.js",
    "file/src/content/helpers.js.html",
    "src/content/helpers.js",
    "file"
  ],
  [
    "src/content/index.js",
    "file/src/content/index.js.html",
    "src/content/index.js",
    "file"
  ],
  [
    "src/content/lib/renderer.js",
    "file/src/content/lib/Renderer.js.html",
    "src/content/lib/Renderer.js",
    "file"
  ],
  [
    "src/content/lib/renderer.js~renderitem",
    "typedef/index.html#static-typedef-RenderItem",
    "src/content/lib/Renderer.js~RenderItem",
    "typedef"
  ],
  [
    "src/content/lib/renderer.js~renderer#component",
    "class/src/content/lib/Renderer.js~Renderer.html#instance-member-component",
    "src/content/lib/Renderer.js~Renderer#component",
    "member"
  ],
  [
    "src/content/lib/renderer.js~renderer#constructor",
    "class/src/content/lib/Renderer.js~Renderer.html#instance-constructor-constructor",
    "src/content/lib/Renderer.js~Renderer#constructor",
    "method"
  ],
  [
    "src/content/lib/renderer.js~renderer#createtreeandattachdom",
    "class/src/content/lib/Renderer.js~Renderer.html#instance-method-createTreeAndAttachDOM",
    "src/content/lib/Renderer.js~Renderer#createTreeAndAttachDOM",
    "method"
  ],
  [
    "src/content/lib/renderer.js~renderer#nodes",
    "class/src/content/lib/Renderer.js~Renderer.html#instance-member-nodes",
    "src/content/lib/Renderer.js~Renderer#nodes",
    "member"
  ],
  [
    "src/content/lib/renderer.js~renderer#render",
    "class/src/content/lib/Renderer.js~Renderer.html#instance-method-render",
    "src/content/lib/Renderer.js~Renderer#render",
    "method"
  ],
  [
    "test/content/timesummarymanager-spec.js",
    "test-file/test/content/TimeSummaryManager-spec.js.html",
    "test/content/TimeSummaryManager-spec.js",
    "testFile"
  ]
]